// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type BaseResp struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}

type LoginData struct {
	Token         string `json:"token"`
	Expire        int64  `json:"expire"`
	RefreshToken  string `json:"refresh_token"`
	RefreshExpire int64  `json:"refresh_expire"`
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	BaseResp
	Data *LoginData `json:"data"`
}

type LogoutReq struct {
	Token string `json:"token"`
}

type RefreshTokenReq struct {
	Refresh_token string `json:"refresh_token"`
}

type RegisterReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type Response struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
	Data string `json:"data"`
}
